### ISSUE TITLE
Proposal: make comptime chameleon immutable

### ISSUE THREAD

**Issue by Selveris** [tr1ckydev/chameleon#8]
Hi there,

First of all thanks for this lib :D !

I would have a small improvement on the comptime api to propose.
The proposed change is to make the comptime Chameleon an immutable struct, which mean at every style change a new struct is produced. This make the use of the lib in comptime environment easier (at least for me '^^)

I have implemented it on a fork, you can find it here: https://github.com/Selveris/chameleon-fork
If you find the change useful feel free to take it

Edit: Also an added bonus (?) is that now every Chameleon struct is a Preset

**Comment by tr1ckydev** [comment]
Thanks for checking out my lib.
Also, the idea you proposed was actually how this lib was earlier. If you go to old commits, it's exactly how I returned the comptime structs. But with the runtime API I had to switch to pointers in comptime as well so as to have a consistent API for both runtimes.

**Comment by Selveris** [comment]
I get your point 

I still wonder though if it is worth as it makes the comptime API harder to use. And in most use case the difference between the two is not noticeable.

The choice is up to you ;)

**Comment by tr1ckydev** [comment]
Hmm, that would need a lot of thinking. But as for now, I have no plans to change the API.
